# -*- coding: utf-8 -*-
"""
test_t9_custom_keys.py - 验证"九键按键设置"对话框生成的 t9.custom.yaml
能被 rime 正确编译并生效 (字母键 u/i/o 映射为九键 2/3/4)。
"""
import ctypes
import os
import re
import shutil
import sys
import time

RIME_DLL = r"d:\desktop\input\weasel\output\Win32\rime.dll"
SHARED_DIR = r"d:\desktop\input\weasel\output\data"
USER_DIR = r"d:\desktop\input\rime-user-t9keys"

if os.path.isdir(USER_DIR):
    shutil.rmtree(USER_DIR)
os.makedirs(USER_DIR, exist_ok=True)

# 与 T9KeySettingsDialog::SaveSchemaEntries 输出完全一致的格式
CUSTOM_YAML = """# T9KeySettings-v1 generated by WeaselDeployer (do not edit the marker line)
patch:
  key_binder/bindings/+:
    - {accept: u, send: '2', when: composing}
    - {accept: i, send: '3', when: composing}
    - {accept: o, send: '4', when: composing}
"""
with open(os.path.join(USER_DIR, "t9.custom.yaml"), "w", encoding="utf-8", newline="") as f:
    f.write(CUSTOM_YAML)

dll = ctypes.CDLL(RIME_DLL)


class RimeTraits(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("shared_data_dir", ctypes.c_char_p),
        ("user_data_dir", ctypes.c_char_p),
        ("distribution_name", ctypes.c_char_p),
        ("distribution_code_name", ctypes.c_char_p),
        ("distribution_version", ctypes.c_char_p),
        ("app_name", ctypes.c_char_p),
        ("modules", ctypes.POINTER(ctypes.c_char_p)),
    ]


class RimeCandidate(ctypes.Structure):
    _fields_ = [
        ("text", ctypes.c_char_p),
        ("comment", ctypes.c_char_p),
        ("reserved", ctypes.c_char_p),
    ]


class RimeMenu(ctypes.Structure):
    _fields_ = [
        ("page_size", ctypes.c_int),
        ("page_no", ctypes.c_int),
        ("is_last_page", ctypes.c_bool),
        ("highlighted_candidate_index", ctypes.c_int),
        ("num_candidates", ctypes.c_int),
        ("candidates", ctypes.POINTER(RimeCandidate)),
        ("select_keys", ctypes.c_char_p),
    ]


class RimeComposition(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int),
        ("cursor_pos", ctypes.c_int),
        ("sel_start", ctypes.c_int),
        ("sel_end", ctypes.c_int),
        ("preedit", ctypes.c_char_p),
    ]


class RimeCommit(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("text", ctypes.c_char_p),
    ]


def STRUCT_INIT(Struct):
    return ctypes.sizeof(Struct) - ctypes.sizeof(ctypes.c_int)


class RimeContext(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("composition", RimeComposition),
        ("menu", RimeMenu),
        ("commit_text_preview", ctypes.c_char_p),
        ("select_labels", ctypes.POINTER(ctypes.c_char_p)),
    ]


dll.RimeSetup.argtypes = [ctypes.POINTER(RimeTraits)]
dll.RimeInitialize.argtypes = [ctypes.POINTER(RimeTraits)]
dll.RimeStartMaintenance.argtypes = [ctypes.c_bool]
dll.RimeIsMaintenancing.argtypes = []
dll.RimeJoinMaintenanceThread.argtypes = []
dll.RimeCreateSession.argtypes = []
dll.RimeFindSession.argtypes = [ctypes.c_uint]
dll.RimeDestroySession.argtypes = [ctypes.c_uint]
dll.RimeProcessKey.argtypes = [ctypes.c_uint, ctypes.c_int, ctypes.c_int]
dll.RimeGetContext.argtypes = [ctypes.c_uint, ctypes.POINTER(RimeContext)]
dll.RimeFreeContext.argtypes = [ctypes.POINTER(RimeContext)]
dll.RimeGetCommit.argtypes = [ctypes.c_uint, ctypes.POINTER(RimeCommit)]
dll.RimeFreeCommit.argtypes = [ctypes.POINTER(RimeCommit)]
dll.RimeSelectSchema.argtypes = [ctypes.c_uint, ctypes.c_char_p]

traits = RimeTraits()
traits.data_size = STRUCT_INIT(RimeTraits)
traits.shared_data_dir = SHARED_DIR.encode("utf-8")
traits.user_data_dir = USER_DIR.encode("utf-8")
traits.distribution_name = b"Weasel T9 Keys Test"
traits.distribution_code_name = b"weasel-t9keys-test"
traits.distribution_version = b"1.0.0"
traits.app_name = b"rime.weasel-t9keys-test"

dll.RimeSetup(ctypes.byref(traits))
dll.RimeInitialize(ctypes.byref(traits))

print("=== start maintenance (deploy with t9.custom.yaml) ===")
dll.RimeStartMaintenance(True)
t0 = time.time()
while dll.RimeIsMaintenancing():
    time.sleep(1)
    if time.time() - t0 > 900:
        print("TIMEOUT waiting maintenance")
        sys.exit(1)
print("maintenance finished in %.1fs" % (time.time() - t0))

session = dll.RimeCreateSession()
if not dll.RimeFindSession(session):
    print("ERROR: create session failed")
    sys.exit(1)
dll.RimeSelectSchema(session, b"t9")


def get_context(sess):
    ctx = RimeContext()
    ctx.data_size = STRUCT_INIT(RimeContext)
    if not dll.RimeGetContext(sess, ctypes.byref(ctx)):
        return None
    return ctx


def menu_texts(ctx):
    return [
        ctx.menu.candidates[i].text.decode("utf-8", "replace")
        for i in range(ctx.menu.num_candidates)
    ]


def preedit_of(ctx):
    return ctx.composition.preedit.decode("utf-8", "replace") if ctx.composition.preedit else ""


def press(sess, key, mask=0):
    return dll.RimeProcessKey(sess, key, mask)


def clear_composition(sess):
    XK_BACKSPACE = 0xFF08
    for _ in range(32):
        ctx = get_context(sess)
        if not ctx or not ctx.composition.preedit:
            return
        press(sess, XK_BACKSPACE)


def take_commit(sess):
    commit = RimeCommit()
    commit.data_size = STRUCT_INIT(RimeCommit)
    if dll.RimeGetCommit(sess, ctypes.byref(commit)):
        txt = commit.text.decode("utf-8", "replace") if commit.text else ""
        dll.RimeFreeCommit(ctypes.byref(commit))
        return txt
    return ""


results = []


def check(name, cond, detail=""):
    results.append((name, cond, detail))
    print(("PASS " if cond else "FAIL ") + name + (" | " + detail if detail else ""))


# ---- 测试 1: 编码中按 u i o 映射为 2 3 4 ----
print("\n=== test 1: u/i/o -> 2/3/4 ===")
press(session, ord("2"))  # 先进入编码状态 (when: composing)
for ch in "uio":
    consumed = press(session, ord(ch))
    check("按键 %s 被消费(编码中)" % ch, consumed == 1, "consumed=%d" % consumed)
ctx = get_context(session)
pe = preedit_of(ctx)
texts = menu_texts(ctx)
print("preedit:", pe, "candidates:", texts)
check("2uio 预览栏为拼音", bool(pe) and re.fullmatch(r"[a-zü]+('[a-zü]+)*", pe), repr(pe))
check("2uio 有候选词", len(texts) > 0, str(texts[:5]))
clear_composition(session)

# ---- 测试 2: 2uu (=222) 与 222 候选一致 ----
print("\n=== test 2: 2uu 等效 222 ===")
for ch in "2uu":
    press(session, ord(ch))
ctx = get_context(session)
texts_u = menu_texts(ctx)
clear_composition(session)
for ch in "222":
    press(session, ord(ch))
ctx = get_context(session)
texts_d = menu_texts(ctx)
print("2uu:", texts_u[:5], "222:", texts_d[:5])
check("2uu 与 222 首选一致", bool(texts_u) and texts_u[0] == texts_d[0],
      "%r vs %r" % (texts_u[:1], texts_d[:1]))
clear_composition(session)

# ---- 测试 3: 未映射的字母键不进入编码 (j 无绑定) ----
# express_editor 的既定行为: 编码中遇到无法延长的字符时
# 先上屏当前候选 (consumed=0, 字符直通应用), 编码被清空。
print("\n=== test 3: 未绑定字母键不干扰 ===")
take_commit(session)
press(session, ord("2"))
ctx = get_context(session)
pe_before = preedit_of(ctx)
consumed = press(session, ord("j"))
ctx = get_context(session)
pe_after = preedit_of(ctx)
c = take_commit(session)
print("consumed:", consumed, "preedit:", repr(pe_before), "->", repr(pe_after), "commit:", repr(c))
check("j 键不进入九键编码(编码被上屏清空)",
      pe_before and not pe_after and consumed == 0 and bool(c),
      "%r -> %r commit=%r" % (pe_before, pe_after, c))

# ---- 测试 4: 原有数字输入不受影响 (96636 -> 我们) ----
print("\n=== test 4: 96636 -> 我们 ===")
take_commit(session)  # 清空可能残留的上屏
for ch in "96636":
    press(session, ord(ch))
ctx = get_context(session)
texts = menu_texts(ctx)
check("96636 首选=我们", texts and texts[0] == "我们", str(texts[:5]))
press(session, ord(" "))
c = take_commit(session)
check("96636 上屏=我们", c == "我们", repr(c))

dll.RimeDestroySession(session)

fails = [r for r in results if not r[1]]
print("\n========== SUMMARY: %d/%d PASSED ==========" % (len(results) - len(fails), len(results)))
if fails:
    print("FAILED:", [r[0] for r in fails])
    sys.exit(1)
print("ALL TESTS PASSED")
