# -*- coding: utf-8 -*-
"""
test_t9_custom_always.py - 验证"九键按键设置"新格式 (when: always):
字母键可直接起头输入, 英文模式下不误触。
"""
import ctypes
import os
import re
import shutil
import sys
import time

RIME_DLL = r"d:\desktop\input\weasel\output\rime.dll"  # 64 位, 配合 64 位 Python
SHARED_DIR = r"d:\desktop\input\weasel\output\data"
USER_DIR = r"d:\desktop\input\rime-user-t9always"

if os.path.isdir(USER_DIR):
    shutil.rmtree(USER_DIR)
os.makedirs(USER_DIR, exist_ok=True)

# 与新版 T9KeySettingsDialog::SaveSchemaKeys 输出一致的格式
CUSTOM_YAML = """# T9KeySettings-v1 generated by WeaselDeployer (do not edit the marker line)
patch:
  key_binder/bindings/+:
    - {accept: w, send: '2', when: always}
    - {accept: e, send: '3', when: always}
"""
with open(os.path.join(USER_DIR, "t9.custom.yaml"), "w", encoding="utf-8", newline="") as f:
    f.write(CUSTOM_YAML)
# 跳过首次运行的方案选择
with open(os.path.join(USER_DIR, "default.custom.yaml"), "w", encoding="utf-8", newline="") as f:
    f.write("patch:\n  schema_list:\n    - schema: t9\n")

dll = ctypes.CDLL(RIME_DLL)


class RimeTraits(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("shared_data_dir", ctypes.c_char_p),
        ("user_data_dir", ctypes.c_char_p),
        ("distribution_name", ctypes.c_char_p),
        ("distribution_code_name", ctypes.c_char_p),
        ("distribution_version", ctypes.c_char_p),
        ("app_name", ctypes.c_char_p),
        ("modules", ctypes.POINTER(ctypes.c_char_p)),
    ]


class RimeCandidate(ctypes.Structure):
    _fields_ = [
        ("text", ctypes.c_char_p),
        ("comment", ctypes.c_char_p),
        ("reserved", ctypes.c_char_p),
    ]


class RimeMenu(ctypes.Structure):
    _fields_ = [
        ("page_size", ctypes.c_int),
        ("page_no", ctypes.c_int),
        ("is_last_page", ctypes.c_bool),
        ("highlighted_candidate_index", ctypes.c_int),
        ("num_candidates", ctypes.c_int),
        ("candidates", ctypes.POINTER(RimeCandidate)),
        ("select_keys", ctypes.c_char_p),
    ]


class RimeComposition(ctypes.Structure):
    _fields_ = [
        ("length", ctypes.c_int),
        ("cursor_pos", ctypes.c_int),
        ("sel_start", ctypes.c_int),
        ("sel_end", ctypes.c_int),
        ("preedit", ctypes.c_char_p),
    ]


class RimeCommit(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("text", ctypes.c_char_p),
    ]


def STRUCT_INIT(Struct):
    return ctypes.sizeof(Struct) - ctypes.sizeof(ctypes.c_int)


class RimeContext(ctypes.Structure):
    _fields_ = [
        ("data_size", ctypes.c_int),
        ("composition", RimeComposition),
        ("menu", RimeMenu),
        ("commit_text_preview", ctypes.c_char_p),
        ("select_labels", ctypes.POINTER(ctypes.c_char_p)),
    ]


dll.RimeSetup.argtypes = [ctypes.POINTER(RimeTraits)]
dll.RimeInitialize.argtypes = [ctypes.POINTER(RimeTraits)]
dll.RimeStartMaintenance.argtypes = [ctypes.c_bool]
dll.RimeIsMaintenancing.argtypes = []
dll.RimeJoinMaintenanceThread.argtypes = []
dll.RimeCreateSession.argtypes = []
dll.RimeCreateSession.restype = ctypes.c_void_p
dll.RimeFindSession.argtypes = [ctypes.c_void_p]
dll.RimeDestroySession.argtypes = [ctypes.c_void_p]
dll.RimeProcessKey.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_int]
dll.RimeGetContext.argtypes = [ctypes.c_void_p, ctypes.POINTER(RimeContext)]
dll.RimeFreeContext.argtypes = [ctypes.POINTER(RimeContext)]
dll.RimeGetCommit.argtypes = [ctypes.c_void_p, ctypes.POINTER(RimeCommit)]
dll.RimeFreeCommit.argtypes = [ctypes.POINTER(RimeCommit)]
dll.RimeSelectSchema.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
dll.RimeSetOption.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_bool]

traits = RimeTraits()
traits.data_size = STRUCT_INIT(RimeTraits)
traits.shared_data_dir = SHARED_DIR.encode("utf-8")
traits.user_data_dir = USER_DIR.encode("utf-8")
traits.distribution_name = b"Weasel T9 Always Test"
traits.distribution_code_name = b"weasel-t9always-test"
traits.distribution_version = b"1.0.0"
traits.app_name = b"rime.weasel-t9always-test"

dll.RimeSetup(ctypes.byref(traits))
dll.RimeInitialize(ctypes.byref(traits))

print("=== start maintenance ===")
dll.RimeStartMaintenance(True)
t0 = time.time()
while dll.RimeIsMaintenancing():
    time.sleep(1)
    if time.time() - t0 > 900:
        print("TIMEOUT waiting maintenance")
        sys.exit(1)
print("maintenance finished in %.1fs" % (time.time() - t0))

session = dll.RimeCreateSession()
if not dll.RimeFindSession(session):
    print("ERROR: create session failed")
    sys.exit(1)
dll.RimeSelectSchema(session, b"t9")


def get_context(sess):
    ctx = RimeContext()
    ctx.data_size = STRUCT_INIT(RimeContext)
    if not dll.RimeGetContext(sess, ctypes.byref(ctx)):
        return None
    return ctx


def menu_texts(ctx):
    return [
        ctx.menu.candidates[i].text.decode("utf-8", "replace")
        for i in range(ctx.menu.num_candidates)
    ]


def preedit_of(ctx):
    return ctx.composition.preedit.decode("utf-8", "replace") if ctx.composition.preedit else ""


def press(sess, key, mask=0):
    return dll.RimeProcessKey(sess, key, mask)


def take_commit(sess):
    commit = RimeCommit()
    commit.data_size = STRUCT_INIT(RimeCommit)
    if dll.RimeGetCommit(sess, ctypes.byref(commit)):
        txt = commit.text.decode("utf-8", "replace") if commit.text else ""
        dll.RimeFreeCommit(ctypes.byref(commit))
        return txt
    return ""


def clear_composition(sess):
    for _ in range(32):
        ctx = get_context(sess)
        if not ctx or not ctx.composition.preedit:
            return
        press(sess, 0xFF08)


results = []


def check(name, cond, detail=""):
    results.append((name, cond, detail))
    print(("PASS " if cond else "FAIL ") + name + (" | " + detail if detail else ""))


# ---- 测试 1: 字母键直接起头 (when: always) ----
print("\n=== test 1: 直接按 w 起头 ===")
consumed = press(session, ord("w"))
ctx = get_context(session)
pe = preedit_of(ctx)
texts = menu_texts(ctx)
print("consumed:", consumed, "preedit:", repr(pe), "candidates:", texts[:5])
check("w 直接起头被消费", consumed == 1, "consumed=%d" % consumed)
check("w 起头有候选", len(texts) > 0, str(texts[:5]))
clear_composition(session)

# ---- 测试 2: wee (=233) 与 233 候选一致 ----
print("\n=== test 2: wee 等效 233 ===")
for ch in "wee":
    press(session, ord(ch))
ctx = get_context(session)
texts_w = menu_texts(ctx)
clear_composition(session)
for ch in "233":
    press(session, ord(ch))
ctx = get_context(session)
texts_d = menu_texts(ctx)
print("wee:", texts_w[:5], "233:", texts_d[:5])
check("wee 与 233 首选一致", bool(texts_w) and texts_w[0] == texts_d[0],
      "%r vs %r" % (texts_w[:1], texts_d[:1]))
clear_composition(session)

# ---- 测试 3: 英文模式 (ascii_mode) 下 w 不误触 ----
print("\n=== test 3: 英文模式下不误触 ===")
# 真实 weasel 中英文模式按键根本不会送到引擎, 这里再用引擎级 option 做保守验证
dll.RimeSetOption(session, b"ascii_mode", True)
consumed = press(session, ord("w"))
ctx = get_context(session)
pe = preedit_of(ctx)
print("consumed:", consumed, "preedit:", repr(pe))
check("英文模式下 w 不被输入法消费", consumed == 0, "consumed=%d" % consumed)
check("英文模式下 w 不进入编码", pe == "", repr(pe))
dll.RimeSetOption(session, b"ascii_mode", False)
clear_composition(session)

# ---- 测试 4: 原数字输入不受影响 ----
print("\n=== test 4: 96636 -> 我们 ===")
take_commit(session)
for ch in "96636":
    press(session, ord(ch))
ctx = get_context(session)
texts = menu_texts(ctx)
check("96636 首选=我们", texts and texts[0] == "我们", str(texts[:5]))
press(session, ord(" "))
c = take_commit(session)
check("96636 上屏=我们", c == "我们", repr(c))

dll.RimeDestroySession(session)

fails = [r for r in results if not r[1]]
print("\n========== SUMMARY: %d/%d PASSED ==========" % (len(results) - len(fails), len(results)))
if fails:
    print("FAILED:", [r[0] for r in fails])
    sys.exit(1)
print("ALL TESTS PASSED")
